# generated by chatgpt
from scipy.special import comb

'''
I have a jar with red and blue balls. 
There are 31 red balls and 7500 blue balls. 
I randomly take out 15 balls from the jar. 
What is the probability that at least 3 of the balls are red?
This code actually works.
'''
def probability_at_least_k_red(k, n, N_red, N_blue):
    probability = 0
    for i in range(k, n + 1):
        probability += (comb(n, i) * comb(N_red, i) * comb(N_blue, n - i)) / comb(N_red + N_blue, n)
    return probability

def at_least_N_red(num_red):
    # Given information
    N_red_balls = 31
    N_blue_balls = 7500
    total_draws = 15

    # Calculate probability of at least num_red red balls
    probability_at_least_N_red = probability_at_least_k_red(num_red, total_draws, N_red_balls, N_blue_balls)

    print(f"The probability of drawing at least {num_red} red balls out of {total_draws} draws is: {probability_at_least_N_red:.6f}")

at_least_N_red(4)

'''
I have a jar with 5625 red balls and 1875 blue ball. 
I draw out 15 balls. 
What is the probability that all 15 balls are red?
'''
from scipy.special import comb

def probability_all_red(n, N_red, N_blue):
    return (comb(n, n) * comb(N_red, n) * comb(N_blue, 0)) / comb(N_red + N_blue, n)

def all_red():

    # Given information
    N_red_balls = 5625
    N_blue_balls = 1875
    total_draws = 15

    # Calculate probability of all 15 balls being red
    probability_all_15_red = probability_all_red(total_draws, N_red_balls, N_blue_balls)

    print(f"The probability of drawing all 15 balls as red is: {probability_all_15_red:.6f}")
all_red()